name: Version Bump (Simple)

on:
  push:
    branches:
      - develop
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        run: |
          # ブランチ名抽出
          branch=${GITHUB_REF##*/}
          if [ "$branch" = "develop" ]; then
            bump="patch"
          elif [ "$branch" = "main" ]; then
            if echo "${{ github.event.head_commit.message }}" | grep -qi "\[major\]"; then
              bump="major"
            else
              bump="minor"
            fi
          else
            exit 0
          fi

          # VERSION ファイルがなければ初期値 0.0.0
          file="VERSION"
          current=$( [ -f "$file" ] && cat "$file" || echo "0.0.0" )
          IFS='.' read -r maj min pat <<< "$current"

          case $bump in
            major)
              maj=$((maj + 1)); min=0; pat=0
              ;;
            minor)
              min=$((min + 1)); pat=0
              ;;
            patch)
              pat=$((pat + 1))
              ;;
          esac
          new_ver="${maj}.${min}.${pat}"
          echo "$new_ver" > "$file"
          echo "New version: $new_ver"

          # Git 設定、コミット、タグ作成＆ push
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$file"
          git commit -m "Bump version to $new_ver" || exit 0
          git tag "$new_ver"
          git push origin HEAD --follow-tags
